import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from '@/components';

const geistRegular = localFont({
	src: './fonts/Geist-Regular.ttf',
	variable: '--font-geist-regular',
	weight: '100 400 500 800',
});
const geistBold = localFont({
	src: './fonts/Geist-Bold.ttf',
	variable: '--font-geist-bold',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'e-mint monocrom theme',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head></head>
			<body className={`${geistRegular.variable} ${geistBold.variable}`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
